export const ModelData = [
  {
    id: "pyramid",
    title: "Pyramid of Khafre",
    description: "The Pyramid of Khafre is the second-tallest and second-largest of the Ancient Egyptian Pyramids of Giza. Built around 2570 BC as a tomb for the Pharaoh Khafre, it stands as a testament to ancient Egyptian engineering and architectural prowess. The pyramid originally stood 143.5 meters tall and was covered in smooth Tura limestone casing stones.",
    url: "https://cdn.britannica.com/06/122506-050-C8E03A8A/Pyramid-of-Khafre-Giza-Egypt.jpg",
    scale: 0.02,
    labels: [
      {
        id: 1,
        name: "Base",
        description: "The solid foundation of the pyramid, supporting its immense weight and structure with precision-cut limestone blocks.",
        from: [-1, 0, -1],
        to: [25, 5, 25],
        dimensions: {
          height: 5,
          width: 6,
          depth: 6,
          unit: "m",
        },
      },
      {
        id: 2,
        name: "Entrance Passage",
        description: "A series of descending passages that allow access to the inner chambers of the pyramid.",
        from: [-2, 0, -2],
        to: [15, 6, 25],
        dimensions: {
          height: 5,
          width: 4,
          depth: 4,
          unit: "m",
        },
      },
      {
        id: 3,
        name: "King's Chamber",
        description: "The innermost chamber of the pyramid, believed to be the burial place of Pharaoh Khafre.",
        from: [-1, 5, -1],
        to: [21, 10, 21],
        dimensions: {
          height: 5,
          width: 2,
          depth: 2,
          unit: "m",
        },
      },
      {
        id: 4,
        name: "Queen's Chamber",
        description: "Another chamber within the pyramid, possibly intended for the queen or other members of the royal family.",
        from: [-2, 3, -2],
        to: [12, 5, 32],
        dimensions: {
          height: 2,
          width: 4,
          depth: 4,
          unit: "m",
        },
      },
      {
        id: 5,
        name: "Grand Gallery",
        description: "A long corridor leading to the King's Chamber, featuring a steep incline and elaborate construction.",
        from: [-2, 0, -2],
        to: [22, 15, 2],
        dimensions: {
          height: 5,
          width: 4,
          depth: 4,
          unit: "m",
        },
      },
      {
        id: 6,
        name: "Upper Passage",
        description: "Ascending passages that connect various chambers within the pyramid structure.",
        from: [-2, 0, -2],
        to: [16, 25, 2],
        dimensions: {
          height: 5,
          width: 4,
          depth: 4,
          unit: "m",
        },
      },
      {
        id: 7,
        name: "Ventilation Shaft",
        description: "Ancient air shafts that may have served astronomical or religious purposes.",
        from: [-2, 0, -2],
        to: [22, 25, 12],
        dimensions: {
          height: 5,
          width: 4,
          depth: 4,
          unit: "m",
        },
      },
    ],
  },
  {
    id: "angel_statue",
    title: "Angel Statue",
    description: "This elegant angel statue represents classical European religious sculpture, capturing the serene and peaceful essence of celestial beings. The detailed craftsmanship showcases intricate carving of feathers, facial features, and flowing robes. Such statues were common in European gardens and cemeteries, symbolizing divine protection and spiritual peace.",
    url: "https://t3.ftcdn.net/jpg/05/76/00/82/360_F_576008288_Sw1JWdLINBO8kSoX8mm2GtK9NbO2T6wQ.jpg",
    scale: 0.2,
    labels: [
      {
        id: 1,
        name: "Statue Head",
        description: "The head of the angel statue, showcasing intricate details of the angel's serene face and flowing hair.",
        from: [0, 16, 0],
        to: [-5, 16, -4],
        dimensions: {
          height: 0.3,
          width: 0.25,
          depth: 0.2,
          unit: "m",
        },
      },
      {
        id: 2,
        name: "Left Wing",
        description: "The left wing of the angel, beautifully crafted to show individual feathers and their delicate texture.",
        from: [-1, 15, 0],
        to: [-6, 15, 4],
        dimensions: {
          height: 0.5,
          width: 1.2,
          depth: 0.2,
          unit: "m",
        },
      },
      {
        id: 3,
        name: "Right Wing",
        description: "The right wing of the angel, mirroring the left with equal craftsmanship and attention to detail.",
        from: [1, 15, 0],
        to: [6, 15, 4],
        dimensions: {
          height: 0.5,
          width: 1.2,
          depth: 0.2,
          unit: "m",
        },
      },
      {
        id: 4,
        name: "Base of the Statue",
        description: "The ornate pedestal on which the angel statue stands, often inscribed with dedications or prayers.",
        from: [0, -1, 0],
        to: [5, -1, 4],
        dimensions: {
          height: 0.1,
          width: 0.6,
          depth: 0.6,
          unit: "m",
        },
      },
      {
        id: 5,
        name: "Statue Hands",
        description: "The hands of the angel, posed in prayer or blessing, adding to the overall serene appearance.",
        from: [0, 12, 0],
        to: [5, 8, 4],
        dimensions: {
          height: 0.2,
          width: 0.1,
          depth: 0.1,
          unit: "m",
        },
      },
      {
        id: 6,
        name: "Robes and Garments",
        description: "The flowing robes of the angel, carved with careful attention to fabric folds and movement.",
        from: [0, 0, 0],
        to: [5, 0, 4],
        dimensions: {
          height: 0.15,
          width: 0.1,
          depth: 0.2,
          unit: "m",
        },
      },
    ],
    dimensions: {
      height: 1.8,
      width: 0.5,
      depth: 0.5,
      scale: 0.2,
      unit: "m",
    },
  },
  {
    id: "terracotta_warrior",
    title: "Terracotta Warrior",
    description: "The Terracotta Warriors are a collection of clay sculptures depicting the armies of Qin Shi Huang, the first Emperor of China. Created around 210 BC, over 8,000 soldiers were buried with the emperor to protect him in his afterlife. Each warrior has unique facial features, making them one of the most significant archaeological discoveries of the 20th century.",
    url: "https://smarthistory.org/wp-content/uploads/2019/08/terracotta.jpg",
    scale: 0.2,
    labels: [
      {
        id: 1,
        name: "Warrior Head",
        description: "The head of the terracotta warrior, featuring unique facial features and a detailed topknot hairstyle typical of Qin dynasty soldiers.",
        from: [0, 35, 0],
        to: [10, 35, 10],
        dimensions: {
          height: 0.3,
          width: 0.25,
          depth: 0.2,
          unit: "m",
        },
      },
      {
        id: 2,
        name: "Armor Plates",
        description: "The protective armor covering the warrior's torso, showcasing the military technology of ancient China.",
        from: [-1, 20, 0],
        to: [-6, 20, 4],
        dimensions: {
          height: 0.5,
          width: 0.8,
          depth: 0.3,
          unit: "m",
        },
      },
      {
        id: 3,
        name: "Right Arm",
        description: "The right arm positioned for holding weapons, demonstrating the warrior's battle-ready stance.",
        from: [1, 15, 0],
        to: [6, 15, 4],
        dimensions: {
          height: 0.5,
          width: 0.3,
          depth: 0.2,
          unit: "m",
        },
      },
      {
        id: 4,
        name: "Base Platform",
        description: "The sturdy base supporting the warrior statue, representing the ground upon which they stood guard.",
        from: [0, -1, 0],
        to: [5, -1, 4],
        dimensions: {
          height: 0.1,
          width: 0.6,
          depth: 0.6,
          unit: "m",
        },
      },
      {
        id: 5,
        name: "Warrior Hands",
        description: "The hands of the warrior, originally designed to hold bronze weapons that have since decomposed.",
        from: [0, 12, 0],
        to: [5, 8, 4],
        dimensions: {
          height: 0.2,
          width: 0.1,
          depth: 0.1,
          unit: "m",
        },
      },
      {
        id: 6,
        name: "Battle Shoes",
        description: "The footwear of the warrior, showing the practical military boots worn by Qin dynasty soldiers.",
        from: [0, 0, 0],
        to: [5, 0, 4],
        dimensions: {
          height: 0.15,
          width: 0.1,
          depth: 0.2,
          unit: "m",
        },
      },
    ],
    dimensions: {
      height: 1.8,
      width: 0.5,
      depth: 0.5,
      scale: 0.2,
      unit: "m",
    },
  },
  {
    id: "lowpoly_victorian_props_with_customizable_psd",
    title: "Victorian Era Props",
    description: "A collection of authentic Victorian-era artifacts from the 19th century British Empire period. These items include furniture, decorative objects, and household items that showcase the ornate and elaborate design aesthetic of the Victorian era, known for its industrial innovation and decorative arts.",
    url: "https://media.sketchfab.com/models/8e790a9b805a486fb7f8d46a462b14e8/thumbnails/d322e374dfb84625ad79259f1eef2603/6c2b7ac5a4e1403aa71d631a6c3df5f7.jpeg",
    scale: 0.15,
    labels: [
      {
        id: 1,
        name: "Victorian Chair",
        description: "An ornately carved wooden chair featuring the elaborate decorative style typical of Victorian furniture.",
        from: [-2, 0, -2],
        to: [8, 8, 8],
        dimensions: {
          height: 0.9,
          width: 0.5,
          depth: 0.5,
          unit: "m",
        },
      },
      {
        id: 2,
        name: "Decorative Table",
        description: "A Victorian-era side table with intricate woodwork and possibly marble or glass top.",
        from: [3, 0, -2],
        to: [12, 6, 8],
        dimensions: {
          height: 0.7,
          width: 0.8,
          depth: 0.8,
          unit: "m",
        },
      },
      {
        id: 3,
        name: "Gas Lamp",
        description: "An authentic Victorian gas lamp that would have illuminated 19th century homes.",
        from: [-3, 10, -1],
        to: [6, 18, 6],
        dimensions: {
          height: 0.4,
          width: 0.2,
          depth: 0.2,
          unit: "m",
        },
      },
      {
        id: 4,
        name: "Ornamental Vase",
        description: "A decorative porcelain or ceramic vase featuring Victorian floral patterns and gilt accents.",
        from: [2, 7, 2],
        to: [10, 12, 10],
        dimensions: {
          height: 0.3,
          width: 0.15,
          depth: 0.15,
          unit: "m",
        },
      },
    ],
    dimensions: {
      height: 1.5,
      width: 1.2,
      depth: 1.0,
      scale: 0.15,
      unit: "m",
    },
  },
  {
    id: "greek_jar",
    title: "Ancient Greek Amphora",
    description: "A beautifully decorated ancient Greek amphora (storage jar) used for storing wine, olive oil, and other goods. These vessels feature the iconic black-figure or red-figure pottery technique, often depicting mythological scenes, athletic competitions, or daily life in ancient Greece. Dating from 6th-4th century BC.",
    url: "https://images.metmuseum.org/CRDImages/gr/original/DP116936.jpg",
    scale: 0.25,
    labels: [
      {
        id: 1,
        name: "Jar Neck",
        description: "The narrow neck of the amphora, designed to control the flow of liquids and prevent spillage.",
        from: [0, 18, 0],
        to: [8, 18, 8],
        dimensions: {
          height: 0.3,
          width: 0.15,
          depth: 0.15,
          unit: "m",
        },
      },
      {
        id: 2,
        name: "Decorative Panel",
        description: "The main decorated area featuring black-figure scenes of Greek mythology or daily life.",
        from: [-2, 8, -2],
        to: [10, 8, 10],
        dimensions: {
          height: 0.4,
          width: 0.35,
          depth: 0.35,
          unit: "m",
        },
      },
      {
        id: 3,
        name: "Handles",
        description: "The characteristic twin handles used for carrying and pouring, elegantly curved and attached to the vessel.",
        from: [-4, 12, 0],
        to: [2, 12, 8],
        dimensions: {
          height: 0.25,
          width: 0.1,
          depth: 0.35,
          unit: "m",
        },
      },
      {
        id: 4,
        name: "Body of Amphora",
        description: "The main body of the jar, featuring intricate painted scenes and geometric patterns.",
        from: [-1, 4, -1],
        to: [10, 4, 10],
        dimensions: {
          height: 0.5,
          width: 0.4,
          depth: 0.4,
          unit: "m",
        },
      },
      {
        id: 5,
        name: "Base",
        description: "The pointed or rounded base of the amphora, sometimes designed to be placed in sand or a stand.",
        from: [0, 0, 0],
        to: [8, 0, 8],
        dimensions: {
          height: 0.15,
          width: 0.2,
          depth: 0.2,
          unit: "m",
        },
      },
    ],
    dimensions: {
      height: 0.6,
      width: 0.4,
      depth: 0.4,
      scale: 0.25,
      unit: "m",
    },
  },
  {
    id: "budha_statue",
    title: "Buddha Statue",
    description: "A serene Buddha sculpture representing enlightenment, peace, and spiritual awakening. This statue showcases traditional Buddhist artistic styles from East Asian temple architecture, typically depicting Buddha in meditation pose. Such statues have been central to Buddhist worship and meditation practices for over 2,500 years.",
    url: "https://thumbs.dreamstime.com/z/buddha-statue-japan-kitain-temple-kawagoe-city-disciples-around-him-arhats-gohyaku-rakan-51140413.jpg",
    scale: 0.18,
    labels: [
      {
        id: 1,
        name: "Buddha Head",
        description: "The serene head of Buddha featuring the ushnisha (cranial bump) symbolizing enlightened wisdom.",
        from: [0, 22, 0],
        to: [8, 22, 8],
        dimensions: {
          height: 0.35,
          width: 0.25,
          depth: 0.25,
          unit: "m",
        },
      },
      {
        id: 2,
        name: "Meditation Hands",
        description: "The hands positioned in dhyana mudra, the meditation gesture symbolizing concentration and tranquility.",
        from: [-1, 12, -1],
        to: [9, 12, 9],
        dimensions: {
          height: 0.2,
          width: 0.3,
          depth: 0.2,
          unit: "m",
        },
      },
      {
        id: 3,
        name: "Robes",
        description: "The flowing monastic robes draped over Buddha's body, carved with intricate folds and patterns.",
        from: [-2, 8, -2],
        to: [10, 8, 10],
        dimensions: {
          height: 0.6,
          width: 0.5,
          depth: 0.4,
          unit: "m",
        },
      },
      {
        id: 4,
        name: "Lotus Throne",
        description: "The lotus flower base upon which Buddha sits, symbolizing purity and spiritual awakening.",
        from: [-1, 0, -1],
        to: [9, 0, 9],
        dimensions: {
          height: 0.2,
          width: 0.6,
          depth: 0.6,
          unit: "m",
        },
      },
      {
        id: 5,
        name: "Crossed Legs",
        description: "Buddha's legs in lotus position (padmasana), the traditional meditation posture.",
        from: [-1, 3, -1],
        to: [9, 3, 9],
        dimensions: {
          height: 0.3,
          width: 0.5,
          depth: 0.5,
          unit: "m",
        },
      },
    ],
    dimensions: {
      height: 1.2,
      width: 0.7,
      depth: 0.6,
      scale: 0.18,
      unit: "m",
    },
  },
  {
    id: "vertebrate_tyrannosaurus_rex_skull_mote",
    title: "Tyrannosaurus Rex Skull",
    description: "The massive skull of a Tyrannosaurus Rex, one of the largest carnivorous dinosaurs that lived 68-66 million years ago during the Late Cretaceous period. This apex predator had one of the most powerful bites of any land animal, with teeth up to 12 inches long. The T-Rex skull showcases evolutionary adaptations for hunting and consuming large prey.",
    url: "https://assets.superhivemarket.com/store/productimage/1015772/image/xlarge_og-ecde679694b3a256a7ea486fc3f3da45.png",
    scale: 0.12,
    labels: [
      {
        id: 1,
        name: "Massive Jaw",
        description: "The powerful lower jaw capable of exerting up to 12,800 pounds of bite force, the strongest of any land animal.",
        from: [-2, 4, -2],
        to: [18, 4, 18],
        dimensions: {
          height: 0.4,
          width: 1.2,
          depth: 0.6,
          unit: "m",
        },
      },
      {
        id: 2,
        name: "Serrated Teeth",
        description: "Banana-shaped teeth up to 12 inches long with serrated edges designed for tearing flesh.",
        from: [2, 6, -1],
        to: [14, 6, 8],
        dimensions: {
          height: 0.3,
          width: 0.8,
          depth: 0.15,
          unit: "m",
        },
      },
      {
        id: 3,
        name: "Eye Sockets",
        description: "Large forward-facing eye sockets indicating binocular vision for hunting prey.",
        from: [-3, 12, 2],
        to: [8, 12, 10],
        dimensions: {
          height: 0.25,
          width: 0.3,
          depth: 0.2,
          unit: "m",
        },
      },
      {
        id: 4,
        name: "Cranium",
        description: "The brain case housing one of the largest brains relative to body size among dinosaurs.",
        from: [-2, 14, 0],
        to: [10, 14, 12],
        dimensions: {
          height: 0.5,
          width: 0.6,
          depth: 0.7,
          unit: "m",
        },
      },
      {
        id: 5,
        name: "Nasal Cavity",
        description: "Large nasal openings suggesting a highly developed sense of smell for tracking prey.",
        from: [1, 10, -2],
        to: [12, 10, 6],
        dimensions: {
          height: 0.3,
          width: 0.4,
          depth: 0.25,
          unit: "m",
        },
      },
    ],
    dimensions: {
      height: 1.5,
      width: 1.3,
      depth: 0.8,
      scale: 0.12,
      unit: "m",
    },
  },
  {
    id: "roman_helmet",
    title: "Roman Military Helmet",
    description: "An authentic Roman legionary helmet (galea) featuring a distinctive red horsehair crest. These helmets were used by Roman soldiers during the height of the Roman Empire's military campaigns from 1st century BC to 4th century AD. The design provided excellent protection while allowing good visibility and hearing for battlefield communication.",
    url: "https://thumbs.dreamstime.com/b/roman-helmet-red-crest-white-background-front-view-d-illustration-roman-helmet-red-crest-white-front-view-d-126283476.jpg",
    scale: 0.22,
    labels: [
      {
        id: 1,
        name: "Horsehair Crest",
        description: "The distinctive red horsehair plume running across the helmet, indicating rank and making soldiers appear taller and more intimidating.",
        from: [-1, 18, 0],
        to: [9, 18, 8],
        dimensions: {
          height: 0.3,
          width: 0.5,
          depth: 0.15,
          unit: "m",
        },
      },
      {
        id: 2,
        name: "Bronze Bowl",
        description: "The main protective dome of the helmet, typically made of bronze or iron with a polished finish.",
        from: [-2, 12, -2],
        to: [10, 12, 10],
        dimensions: {
          height: 0.25,
          width: 0.3,
          depth: 0.3,
          unit: "m",
        },
      },
      {
        id: 3,
        name: "Cheek Guards",
        description: "Hinged protective plates that shield the sides of the face while allowing jaw movement for speaking.",
        from: [-3, 8, -1],
        to: [7, 8, 9],
        dimensions: {
          height: 0.2,
          width: 0.15,
          depth: 0.25,
          unit: "m",
        },
      },
      {
        id: 4,
        name: "Neck Guard",
        description: "The rear flange protecting the neck from downward strikes and projectiles.",
        from: [0, 10, 6],
        to: [8, 10, 14],
        dimensions: {
          height: 0.15,
          width: 0.3,
          depth: 0.2,
          unit: "m",
        },
      },
      {
        id: 5,
        name: "Brow Ridge",
        description: "The reinforced front edge providing extra protection for the forehead and deflecting blows.",
        from: [-1, 11, -3],
        to: [9, 11, 3],
        dimensions: {
          height: 0.08,
          width: 0.3,
          depth: 0.1,
          unit: "m",
        },
      },
    ],
    dimensions: {
      height: 0.35,
      width: 0.25,
      depth: 0.3,
      scale: 0.22,
      unit: "m",
    },
  },
];